apiVersion: apps/v1
kind: Deployment
metadata :
  name : tomcat-app-deployment
spec: 
  selector:
    matchLabels:
      app: tomcat-app
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
        - name: tomcat-app
          image: ayushigupta1496/java-app:{{BUILD_TAG}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: tomcat-appsvc
spec:
  selector:
    app: tomcat-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort


